# Generated by Django 5.0.2 on 2024-02-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='blog.author'),
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=63)),
                ('text', models.TextField()),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentaries', to='blog.post')),
            ],
        ),
    ]
