# Generated by Django 5.0.2 on 2024-02-17 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
